[package]
name = "rust-java-jni-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = { version = "0.21.1", features = ["invocation"] }
actix-web = "4.2.1"
actix-cors = "0.6.4"
tokio = { version = "1.0.0", default-features = false }
